/*
 *  PVImageWindowController.h
 *  CouchPreview
 *
 *  Created by Hugo Camboulive on 22/05/09.
 *  Copyright 2009 Université du Maine - IUP MIME. All rights reserved.
 *
 */

#import <Quartz/Quartz.h>

@class PVNSSplitView;
@class PVIKImageBrowserView;
@class PVGrippyWindow;
@class PVImageInspector;
@class PVImageElement;
@class PVIKImageView;

@interface PVImageWindowController : NSWindowController <IKSlideshowDataSource>
{
	PVNSSplitView *_splitView;
	PVIKImageView *_imageView;
	NSScrollView *_imageViewScrollView;
	PVIKImageBrowserView *_imageBrowserView;
	NSScrollView *_imageBrowserViewScrollView;
	NSPopUpButton *_actionPopup;
	NSMenu *_contextMenu;
	NSView *_splitViewDragWidget;
	id _bookmarkPanel;
	NSTextField *_bookmarkLabelField;
	PVGrippyWindow *_grippyWindow;
	PVImageElement *_currentImageElement;
	id _imageBrowserDataSource;
	int _thumbnailSize;
	int _browserViewSortOrder;
	BOOL _windowSizeIsNotStandard;
	PVImageInspector *_imageInspector;
	BOOL _slideshowRunning;
	unsigned int _slideshowSelection;
	NSMutableDictionary *_resizeImageState;
	NSDictionary *_toolbarItems;
	NSString *_selectionMode;
	BOOL _doAnimateSwipeTransition;
	id _activeSwipeTransition;
	PVImageElement *_pendingSwipeElem;
	int _pendingSwipeDirection;
	int _lastLargeThumbnailSelIndex;
}

+ (void)initialize;
- (id)initWithWindowNibName:(id)fp8;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)currentImageElement;
- (void)setCurrentImageElement:(id)fp8;
- (int)thumbnailSize;
- (void)setThumbnailSize:(int)fp8;
- (id)selectedImageElements;
- (id)selectedImageContainers;
- (void)windowDidLoad;
- (void)showWindow:(id)fp8;
- (void)windowWillClose:(id)fp8;
- (void)windowDidBecomeMain:(id)fp8;
- (id)windowTitleForDocumentDisplayName:(id)fp8;
- (void)windowDidResize:(id)fp8;
- (BOOL)windowShouldZoom:(id)fp8 toFrame:(struct _NSRect)fp12;
- (struct _NSRect)windowWillUseStandardFrame:(id)fp8 defaultFrame:(struct _NSRect)fp12;
- (BOOL)validateMenuItem:(id)fp8;
- (void)toggleImageBackgroundShown:(id)fp8;
- (void)doZoomIn:(id)fp8;
- (void)doZoomOut:(id)fp8;
- (void)doZoomToSelection:(id)fp8;
- (void)doZoomToFit:(id)fp8;
- (void)doZoomToScale:(id)fp8;
- (void)actualSize:(id)fp8;
- (void)altActualSize:(id)fp8;
- (void)autoZoom:(id)fp8;
- (void)openScaleFactorPanel:(id)fp8;
- (void)doGoToNextPage:(id)fp8;
- (void)doGoToPreviousPage:(id)fp8;
- (void)doGoToFirstPage:(id)fp8;
- (void)doGoToLastPage:(id)fp8;
- (void)rotateRight:(id)fp8;
- (void)rotateLeft:(id)fp8;
- (void)flipHorizontal:(id)fp8;
- (void)flipVertical:(id)fp8;
- (void)crop:(id)fp8;
- (void)setFreeTextAnnotation:(id)fp8;
- (void)setCircleAnnotation:(id)fp8;
- (void)setRectAnnotation:(id)fp8;
- (void)setArrowAnnotation:(id)fp8;
- (void)scrollTool:(id)fp8;
- (void)selectTool:(id)fp8;
- (void)setRectSelection:(id)fp8;
- (void)setEllipticalSelection:(id)fp8;
- (void)setLassoSelection:(id)fp8;
- (void)cropTool:(id)fp8;
- (void)annotateTool:(id)fp8;
- (void)setSmartLasso:(id)fp8;
- (void)setMagicWand:(id)fp8;
- (void)doSearchField:(id)fp8;
- (void)slideshow:(id)fp8;
- (void)toggleDrawer:(id)fp8;
- (void)addBookmark:(id)fp8;
- (void)addBookMarkAdd:(id)fp8;
- (void)addBookMarkCancel:(id)fp8;
- (void)imageSizing:(id)fp8;
- (void)imageCorrection:(id)fp8;
- (void)assignProfile:(id)fp8;
- (void)matchToProfile:(id)fp8;
- (void)doPrint:(id)fp8;
- (void)printDocument:(id)fp8;
- (void)showInspectorWindow:(id)fp8;
- (void)getInfo:(id)fp8;
- (void)sortByName:(id)fp8;
- (void)sortByFullpath:(id)fp8;
- (void)sortByDate:(id)fp8;
- (void)sortByKind:(id)fp8;
- (void)sortBySize:(id)fp8;
- (void)sortByKeyword:(id)fp8;
- (void)sortIgnore:(id)fp8;
- (void)mailSelection:(id)fp8;
- (void)sendSelectionToIPhoto:(id)fp8;
- (void)sendSelectionToAperture:(id)fp8;
- (void)saveSelectedImages:(id)fp8;
- (void)openInNewWindow:(id)fp8;
- (void)closeImage:(id)fp8;
- (void)moveToTrash:(id)fp8;
- (void)deleteItem:(id)fp8;
- (void)documentWillBeginAddingFiles;
- (void)documentDidEndAddingFiles;
- (void)selectImageElement:(id)fp8;
- (void)documentReplacedImage:(id)fp8 withImage:(id)fp12;
- (void)documentRemovedImages:(id)fp8;
- (void)documentDidInsertImageContainers:(id)fp8 atIndexes:(id)fp12;
- (void)documentChangedImageList;
- (void)documentDidEndSearch;
- (void)documentDidEndSort;
- (void)maskingModeDidEnd;
- (void)swipeWithEvent:(id)fp8;
- (void)imageBrowserSelectionDidChange:(id)fp8;
- (void)imageBrowser:(id)fp8 cellWasRightClickedAtIndex:(unsigned int)fp12 withEvent:(id)fp16;
- (void)imageBrowser:(id)fp8 backgroundWasRightClickedWithEvent:(id)fp12;
- (unsigned int)numberOfSlideshowItems;
- (id)slideshowItemAtIndex:(unsigned int)fp8;
- (id)nameOfSlideshowItemAtIndex:(unsigned int)fp8;
- (BOOL)canExportSlideshowItemAtIndex:(unsigned int)fp8 toApplication:(id)fp12;
- (void)slideshowWillStart;
- (void)slideshowDidStop;
- (void)slideshowDidChangeCurrentIndex:(unsigned int)fp8;
- (BOOL)splitView:(id)fp8 shouldCollapseSubview:(id)fp12 forDoubleClickOnDividerAtIndex:(int)fp16;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:(id)fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (BOOL)splitView:(id)fp8 canCollapseSubview:(id)fp12;
- (void)splitViewDidExpandOrCollapse:(id)fp8;
- (struct _NSRect)splitView:(id)fp8 effectiveRect:(struct _NSRect)fp12 forDrawnRect:(struct _NSRect)fp28 ofDividerAtIndex:(int)fp44;
- (struct _NSRect)splitView:(id)fp8 additionalEffectiveRectOfDividerAtIndex:(int)fp12;
- (void)imageSizer:(id)fp8 concludedWithResult:(unsigned int)fp12 context:(void *)fp16;
- (void)profileHandler:(id)fp8 concludedAssignProfileWithResult:(unsigned int)fp12 context:(void *)fp16;
- (void)profileHandler:(id)fp8 concludedMatchToProfileWithResult:(unsigned int)fp12 context:(void *)fp16;
- (void)printingControllerDidPrint:(id)fp8 success:(BOOL)fp12;
- (void)activityMonitor:(id)fp8 canceledActivityName:(id)fp12 context:(void *)fp16;
- (void)ensureNibIsLoaded;
- (void)setupImageBrowserView;
- (void)setupToolbar;
- (void)setupSplitView;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (void)toolbarWillAddItem:(id)fp8;
- (BOOL)validateToolbarItem:(id)fp8;
- (id)toolbarModeItem;
- (id)toolbarAnnotateItem;
- (void)updateScaleToolbarItem;
- (void)updateSidebarToolbarItem;
- (void)setToolMode:(id)fp8;
- (void)setAnnotationMode:(int)fp8;
- (void)setSearchFieldLabel:(id)fp8;
- (void)updateSearchCountText:(int)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (BOOL)sendSelectionToApp:(id)fp8;
- (void)sizeWindowToImage:(id)fp8;
- (struct _NSSize)sizeOfImageInScreenPixels:(id)fp8;
- (void)ensureDefaultZoomFactor:(id)fp8;
- (id)selectedImageBrowserItems;
- (void)selectImageBrowserItemIgnoringChange:(id)fp8;
- (void)cleanupAfterImageRemoval:(unsigned int)fp8;
- (void)swipeToImageElement:(id)fp8 direction:(int)fp12;
- (void)imageView:(id)fp8 completedSwipe:(id)fp12 toImageElem:(id)fp16;
- (void)processPendingSwipe;
- (void)queueBuildLargeThumbnailTasks;
- (void)startQueueingLargeThumbnailTasks:(id)fp8;
- (void)bookmarkSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)scalePanelDidEnd:(id)fp8 returnCode:(int)fp12;
- (void)activateDocument:(id)fp8;
- (void)imageElementThumbnailChanged:(id)fp8;
- (void)flagsChangedNotification:(id)fp8;
- (void)backgroundColorChanged:(id)fp8;
- (void)resizeNextFile:(id)fp8;
- (void)handleTracerNotification:(id)fp8;
- (int)browserViewSortOrder;
- (void)setBrowserViewSortOrder:(int)fp8;
- (id)imageBrowserView;
- (id)imageView;
- (id)splitView;

@end
